export const enum Site {
    UNKNOWN,

    BLOGTRUYEN,
    TRUYENTRANH8,
    TRUYENTRANHTUAN,
    HOCVIENTRUYENTRANH,
    IZTRUYENTRANH,
    LHMANGA,
    TRUYENTRANHNET,
    TRUYENTRANHMOI,
    MANGAK,
    UPTRUYEN,
    TRUYENTRANHONLINE,
    HAMTRUYEN,

    MANGAFOX,
    KISSMANGA,
    MANGAPARK,
    MANGASEE
}
